// Copyright (C) 2018-2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

#pragma OPENCL EXTENSION cl_khr_fp16 : enable

// Shared constants for the dense BEV scatter.

// Model geometry.
// BEV_H, BEV_W, BEV_C and BEV_MAX_VOXELS come from pp_pillar_config_generated.cl,
// generated by ov_export.py and concatenated ahead of this file.
#define BEV_PLANE (BEV_H * BEV_W)  // cells per channel

// Launch tuning.
// BEV_ROW_WG and BEV_VEC come from pp_tuning_config_generated.cl, which
// ov_export.py writes from [tuning] in ov_config.toml along with the WorkSizes
// that launch this kernel.
//   BEV_ROW_WG  work-items per row work-group, equal to the WorkSizes `local`,
//               with `global` BEV_H times larger.
//   BEV_VEC     consecutive cells handled per write step; divides BEV_W.

#define BEV_X_CHUNKS (BEV_W / BEV_VEC)
