# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

import argparse
import os
import sys
import os.path as osp
import numpy as np
import random
import importlib
import json

import torch
import torch.nn as nn

import openvino as ov
from openvino import Core

from common_infer_utils import (
    _get_template as shared_get_template,
    get_templates as shared_get_templates,
    get_test_data as shared_get_test_data,
    load_yaml_config,
)
import xml.etree.ElementTree as ET

def patch_topk_by_io_and_name(xml_path: str):
    tree = ET.parse(xml_path)
    root = tree.getroot()

    patched = 0

    for layer in root.iter("layer"):

        # 1. TYPE check (must be TopK)
        if layer.get("type") != "TopK":
            continue

        # 2. NAME check (must start with TopK_)
        name = layer.get("name", "")
        if not name.startswith("TopK_"):
            continue

        inp = layer.find("input")
        out = layer.find("output")
        data = layer.find("data")

        if inp is None or out is None or data is None:
            continue

        # 3. IO shape check (your unique signature)
        input_match = False
        output_match = False

        for p in inp.findall("port"):
            dims = [d.text for d in p.findall("dim")]
            if dims == ["-1", "18000", "38416"]:
                input_match = True

        for p in out.findall("port"):
            dims = [d.text for d in p.findall("dim")]
            if dims == ["-1", "18000", "1"]:
                output_match = True

        if not (input_match and output_match):
            continue

        # 4. Apply fix
        changed = False

        if data.get("sort") != "none":
            data.set("sort", "none")
            changed = True

        if data.get("stable") != "false":
            data.set("stable", "false")
            changed = True

        if changed:
            patched += 1

    tree.write(xml_path, encoding="utf-8", xml_declaration=True)

    print(f"[TopK Patch] Patched {patched} TopK_* layers")




os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.join(BASE_DIR, '..', 'Pose_Estimation_Model')
sys.path.append(os.path.join(ROOT_DIR, 'provider'))
sys.path.append(os.path.join(ROOT_DIR, 'utils'))
sys.path.append(os.path.join(ROOT_DIR, 'model'))
sys.path.append(os.path.join(BASE_DIR, 'model', 'pointnet2'))

def get_parser():
    parser = argparse.ArgumentParser(description="Pose Estimation Model Convert to ONNX and OpenVINO (CPU Version)")
    # pem
    parser.add_argument("--device", type=str, default="cpu", help="device to run on (cpu/cuda)")
    parser.add_argument("--model" , type=str, default="pose_estimation_model", help="path to model file")
    parser.add_argument("--config", type=str, default="config/base.yaml", help="path to config file, different config.yaml use different config")
    parser.add_argument("--iter"  , type=int, default=600000, help="epoch num. for testing")
    parser.add_argument("--exp_id", type=int, default=0, help="")
    
    # Set default input parameter, reference demo.sh
    project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '../..'))
    default_cad_path = os.path.join(project_root, 'SAM-6D/Data/Example/obj_000005.ply')
    default_rgb_path = os.path.join(project_root, 'SAM-6D/Data/Example/rgb.png')
    default_depth_path = os.path.join(project_root, 'SAM-6D/Data/Example/depth.png')
    default_camera_path = os.path.join(project_root, 'SAM-6D/Data/Example/camera.json')
    default_output_dir = os.path.join(project_root, 'SAM-6D/Data/Example/outputs')
    default_seg_path = os.path.join(default_output_dir, 'sam6d_results/detection_ism.json')

    parser.add_argument("--output_dir", nargs="?", default=default_output_dir, help="Path to root directory of the output")
    parser.add_argument("--cad_path", nargs="?", default=default_cad_path, help="Path to CAD(mm)")
    parser.add_argument("--rgb_path", nargs="?", default=default_rgb_path, help="Path to RGB image")
    parser.add_argument("--depth_path", nargs="?", default=default_depth_path, help="Path to Depth image(mm)")
    parser.add_argument("--cam_path", nargs="?", default=default_camera_path, help="Path to camera information")
    parser.add_argument("--seg_path", nargs="?", default=default_seg_path, help="Path to segmentation information(generated by ISM)")
    parser.add_argument("--det_score_thresh", type=float, default=0.2, help="The score threshold of detection")
    args_cfg = parser.parse_args()

    return args_cfg

# Config Init
def init():
    args = get_parser()
    exp_name = args.model + '_' + \
        osp.splitext(args.config.split("/")[-1])[0] + '_id' + str(args.exp_id)
    log_dir = osp.join("log", exp_name)

    cfg = load_yaml_config(args.config)

    cfg.exp_name = exp_name
    cfg.device = args.device
    cfg.model_name = args.model
    cfg.log_dir = log_dir
    cfg.test_iter = args.iter

    cfg.output_dir = args.output_dir
    cfg.cad_path = args.cad_path
    cfg.rgb_path = args.rgb_path
    cfg.depth_path = args.depth_path
    cfg.cam_path = args.cam_path
    cfg.seg_path = args.seg_path

    cfg.det_score_thresh = args.det_score_thresh
    
    print(f"Using device: {cfg.device}")

    return cfg


def _get_template(path, cfg, device, tem_index=1):
    return shared_get_template(path, cfg, device, tem_index)


def get_templates(path, cfg, device):
    return shared_get_templates(path, cfg, device)


def get_test_data(rgb_path, depth_path, cam_path, cad_path, seg_path, det_score_thresh, cfg, device):
    return shared_get_test_data(
        rgb_path,
        depth_path,
        cam_path,
        cad_path,
        seg_path,
        det_score_thresh,
        cfg,
        device,
    )

def create_dummy_templates(cfg, device, batch_size=1):
    # create dummy templates for onnx export
    # [ToDo] If using orginial data for fe_wrapper export, failed due to : 
    # [ONNX] feature extraction submodel export failed: too many indices for tensor of dimension 2
    n_template_view = cfg.test_dataset.n_template_view
    img_size = cfg.test_dataset.img_size
    n_sample_template_point = cfg.test_dataset.n_sample_template_point
    
    # rgb_input: (42, 3, 224, 224) - views as batch
    # choose_input: (42, n_sample_point) - per-view choose indices (not channel-concatenated)
    tem_rgb_concat = torch.randn(n_template_view, 3, img_size, img_size, device=device)
    tem_pts_concat = torch.randn(batch_size, n_template_view * n_sample_template_point, 3, device=device)
    tem_choose_concat = torch.randint(0, img_size*img_size, (n_template_view, n_sample_template_point), device=device)
    
    return tem_rgb_concat, tem_pts_concat, tem_choose_concat

def prepare_data(cfg, model, device):
    print("[Pytorch] extracting templates ...")
    tem_path = os.path.join(cfg.output_dir, 'templates')
    all_tem, all_tem_pts, all_tem_choose = get_templates(tem_path, cfg.test_dataset, device)
    with torch.no_grad():
        all_tem_pts, all_tem_feat = model.feature_extraction.get_obj_feats(all_tem, all_tem_pts, all_tem_choose)

    print("[Pytorch] loading input data ...")
    input_data, img, whole_pts, model_points, detections = get_test_data(
        cfg.rgb_path, cfg.depth_path, cfg.cam_path, cfg.cad_path, cfg.seg_path, 
        cfg.det_score_thresh, cfg.test_dataset, device
    )
    ninstance = input_data['pts'].size(0)

    #pytorch infer verification
    print("[Pytorch] running model ...")
    with torch.no_grad():
        input_data['dense_po'] = all_tem_pts.repeat(ninstance,1,1)
        input_data['dense_fo'] = all_tem_feat.repeat(ninstance,1,1)

    print("[Pytorch] model inference success")

    print("[Pytorch] prepare data for model convert...")
    onnx_pem_input_name = ["pts", "rgb", "rgb_choose", "model", "dense_po", "dense_fo"]
    onnx_pem_output_name = ["pred_R", "pred_t", "pred_pose_score"]
    onnx_pem_input = (input_data['pts'], input_data['rgb'], input_data['rgb_choose'], 
                      input_data['model'], input_data['dense_po'], input_data['dense_fo'])

    rgb_input, pts_input, choose_input = create_dummy_templates(cfg, device)
    onnx_fe_input_name = ["rgb_input", "pts_input", "choose_input"]
    onnx_fe_output_name = ["pts_output", "feat_output"]
    onnx_fe_input = (rgb_input, pts_input, choose_input)

    batch_size = -1
    ov_pem_input_name = {"pts":[batch_size,2048,3], 
                        "rgb":[batch_size,3,224,224], 
                        "rgb_choose":[batch_size,2048], 
                        "model":[batch_size,1024,3], 
                        "dense_po":[batch_size,2048,3], 
                        "dense_fo":[batch_size,2048,256]}
    ov_pem_input = {
        "pts": input_data['pts'],
        "rgb": input_data['rgb'],
        "rgb_choose": input_data['rgb_choose'],
        "model": input_data['model'],
        "dense_po": input_data['dense_po'],
        "dense_fo": input_data['dense_fo'],
    }

    ov_fe_input_name = {"rgb_input":[42,3,224,224],
                        "pts_input":[batch_size,210000,3],
                        "choose_input":[42,5000]}
    ov_fe_output_name = {"pts_output":[batch_size,2048,3], 
                        "feat_output":[batch_size,2048,256]}
    ov_fe_input = {
        "rgb_input": rgb_input,
        "pts_input": pts_input,
        "choose_input": choose_input,
    }

    return (onnx_pem_input_name, onnx_pem_output_name, onnx_pem_input,
            onnx_fe_input_name, onnx_fe_output_name, onnx_fe_input,
            ov_pem_input_name, ov_pem_input,
            ov_fe_input_name, ov_fe_output_name, ov_fe_input)

class FeatureExtractionWrapper(nn.Module):
    """feature_extraction get_obj_feats wrapper for onnx export"""
    def __init__(self, feature_extraction):
        super().__init__()
        self.feature_extraction = feature_extraction
    
    def forward(self, rgb_input, pts_input, choose_input):
        """
        export get_obj_feats method - fully batched, no crop/slice
        rgb_input:    (42, 3, H, W)              - all template views as one batch
        pts_input:    (1, 42*n_sample_point, 3)  - template 3-D points
        choose_input: (42, n_sample_point)        - per-template pixel choose indices
        """
        # Reshape to (B=1, T=42, ...) expected by _get_obj_feats_batched.
        # Internally it does view(B*T, ...) -> single ViT forward pass over all 42 views at once.
        rgb_batched    = rgb_input.unsqueeze(0)     # (1, 42, 3, H, W)
        choose_batched = choose_input.unsqueeze(0)  # (1, 42, n_sample_point)
        # pts_input is already (1, 42*n_sample_point, 3); view(B, -1, 3) inside is a no-op
        return self.feature_extraction._get_obj_feats_batched(
            rgb_batched, pts_input, choose_batched,
            self.feature_extraction.npoint
        )

def onnx_model_convert_feature_extraction_submodel(model, onnx_fe_input_name, onnx_fe_output_name, onnx_fe_input, onnx_model_path):
    feature_wrapper = FeatureExtractionWrapper(model.feature_extraction)
    try:
        with torch.no_grad():
            torch.onnx.export(
                feature_wrapper,
                onnx_fe_input,
                onnx_model_path,
                opset_version=20,
                operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK,
                input_names=onnx_fe_input_name,
                # output_names=onnx_fe_output_name,
                dynamic_axes={k: {0: "batch"} for k in onnx_fe_input_name if k != "rgb_input"},
                do_constant_folding=False,
                verbose=False,  # True , for detailed output
                export_params=True,
                keep_initializers_as_inputs=False
            )
        print(f"[ONNX] feature extraction submodel export success: {onnx_model_path}")
        
    except Exception as e:
        print(f"[ONNX] feature extraction submodel export failed: {e}")

def onnx_model_convert_pose_estimation_submodel(model, onnx_pem_input_name, onnx_pem_output_name, onnx_pem_input, onnx_model_path):
    try:
        torch.onnx.export(
            model,
            onnx_pem_input,
            onnx_model_path,
            opset_version=20,
            operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK,
            input_names=onnx_pem_input_name,
            # output_names=onnx_pem_output_name,
            dynamic_axes={k: {0: "batch"} for k in onnx_pem_input_name},
            do_constant_folding=False,
            verbose=False,
            export_params=True,
            keep_initializers_as_inputs=False
        )
        print(f"[ONNX] PEM onnx model export success: {onnx_model_path}")
            
    except Exception as e:
        print(f"[ONNX] export failed : {e}")


def openvino_model_convert_feature_extraction_submodel(core, onnx_fe_model_path, ov_fe_model_path):
    ov_fe_model = core.read_model(onnx_fe_model_path)
    ov.save_model(ov_fe_model, ov_fe_model_path)
    print(f"[OpenVINO] feature extraction submodel convert success: {ov_fe_model_path}")

def openvino_model_convert_pose_estimation_submodel(core, ov_pem_input_name, ov_pem_input, onnx_pem_model_path, ov_pem_model_path, ov_extension_lib_path):
    ov_pem_model = ov.convert_model(onnx_pem_model_path, 
                                    input=ov_pem_input_name,
                                    example_input=ov_pem_input, 
                                    extension=ov_extension_lib_path,
                                    )
    ov.save_model(ov_pem_model, ov_pem_model_path)
    print(f"[OpenVINO] pose estimation submodel convert success: {ov_pem_model_path}")

def main():
    cfg = init()

    random.seed(cfg.rd_seed)
    torch.manual_seed(cfg.rd_seed)

    print(f"cfg.rd_seed:{cfg.rd_seed}")

    # device setting
    device = torch.device(cfg.device)
    print(f"Using device: {device}")

    # model loading
    print(f"=> creating model ...{cfg.model_name}")
    MODEL = importlib.import_module(cfg.model_name)
    model = MODEL.Net(cfg.model)
    model = model.to(device)
    model.eval()
    checkpoint = os.path.join(os.path.dirname((os.path.abspath(__file__))), 'checkpoints', 'sam-6d-pem-base.pth')
    # load checkpoint
    # Fallback: load checkpoint manually using PyTorch (partial/non-strict)
    print("Loading checkpoint using PyTorch fallback method...")
    try:
        checkpoint_data = torch.load(checkpoint, map_location=device)
        state = checkpoint_data.get('state_dict', checkpoint_data)
        if isinstance(state, dict) and 'model' in state and isinstance(state['model'], dict):
            state = state['model']
        # strip common prefixes
        def _strip_prefix(k, prefix):
            return k[len(prefix):] if k.startswith(prefix) else k
        normalized_state = {}
        for k, v in state.items():
            nk = k
            for prefix in ('module.', 'model.', 'net.'):
                nk = _strip_prefix(nk, prefix)
            normalized_state[nk] = v
        model_state = model.state_dict()
        # filter by matching keys and shapes
        filtered_state = {k: v for k, v in normalized_state.items() if k in model_state and v.shape == model_state[k].shape}
        missing_keys = [k for k in model_state.keys() if k not in normalized_state]
        unexpected_keys = [k for k in normalized_state.keys() if k not in model_state]
        print(f"Partial checkpoint load -> matched: {len(filtered_state)}/{len(model_state)}, missing: {len(missing_keys)}, unexpected: {len(unexpected_keys)}")
        model_state.update(filtered_state)
        model.load_state_dict(model_state, strict=False)
        print("Checkpoint loaded with partial matching")
    except Exception as e:
        print(f"Warning: Could not load checkpoint: {e}")
        print("Continuing with uninitialized model weights")

    # prepare data for model convert
    onnx_pem_input_name, onnx_pem_output_name, onnx_pem_input, \
    onnx_fe_input_name, onnx_fe_output_name, onnx_fe_input, \
    ov_pem_input_name, ov_pem_input, \
    ov_fe_input_name, ov_fe_output_name, ov_fe_input = prepare_data(cfg, model, device)

    model_save_path = "model_save"
    os.makedirs(model_save_path, exist_ok=True)
    onnx_pem_model_path = os.path.join(model_save_path, 'onnx_pem_model_cpu.onnx')
    onnx_fe_model_path = os.path.join(model_save_path, 'onnx_fe_model_cpu.onnx')
    ov_pem_model_path = os.path.join(model_save_path, 'ov_pem_model_cpu.xml')
    ov_fe_model_path = os.path.join(model_save_path, 'ov_fe_model_cpu.xml')
    ov_extension_lib_path = './model/ov_pointnet2_op/build/libopenvino_operation_extension.so'

    core = Core()
    core.add_extension(ov_extension_lib_path)

    # onnx model convert
    onnx_model_convert_feature_extraction_submodel(model, onnx_fe_input_name, onnx_fe_output_name, onnx_fe_input, onnx_fe_model_path)
    onnx_model_convert_pose_estimation_submodel(model, onnx_pem_input_name, onnx_pem_output_name, onnx_pem_input, onnx_pem_model_path)

    # # openvino model convert
    openvino_model_convert_feature_extraction_submodel(core, onnx_fe_model_path, ov_fe_model_path)
    openvino_model_convert_pose_estimation_submodel(core, ov_pem_input_name, ov_pem_input, onnx_pem_model_path, ov_pem_model_path, ov_extension_lib_path)
    patch_topk_by_io_and_name(ov_pem_model_path)

if __name__ == "__main__":
    main()
