#!/usr/bin/env python3

from test_definition_base import CommonTestTraits
from test_definition_base import TestParamsProviderBase
import utils


class TestTraits (CommonTestTraits):
    @property
    def operator_ir_type_string(self):
        return 'ReLU'

    @property
    def test_params_provider_class(self):
        return TestParamsProvider

    @property
    def cpp_test_filename(self):
        return 'activation_slt.cpp'

    @property
    def cpp_test_file_begin_tag(self):
        return '{AUTOGENERATED_TESTS_BEGIN_TAG_RELU}'

    @property
    def cpp_test_file_end_tag(self):
        return '{AUTOGENERATED_TESTS_END_TAG_RELU}'

    @property
    def template_filename(self):
        return 'relu.cpp.jinja2'

    @property
    def default_cpp_test_class_name(self):
        return 'ActivationLayerTest'


class TestParamsProvider (TestParamsProviderBase):
    def __init__(self, list_of_equal_operators, test_traits):
        super().__init__(list_of_equal_operators, test_traits)

    @property
    def cpp_shape(self):
        return 'std::pair<std::vector<size_t>, std::vector<size_t>>{{{}, 0}}'.format(
            utils.cpp_list_from_tuple_of_ints(self.op.input_ports[0].shape)
        )
