#!/bin/bash
# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

GET_ROOT_DIR="git rev-parse --show-toplevel"
ROOT_DIR=$(eval $GET_ROOT_DIR)
if [ -z "$ROOT_DIR" ]; then
    cd ../..
    ROOT_DIR=$(eval $GET_ROOT_DIR)
fi
PRE_PUSH_IMPL_DIR=$ROOT_DIR/modules/nvidia_plugin/utils
cd $PRE_PUSH_IMPL_DIR
./pre-push-impl.sh
exit $?
