# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# SAM 3D Objects — OpenVINO Enablement Support Package
"""
Python support package for OpenVINO-enabled SAM 3D Objects inference.

Provides:
- config: centralized model constants and diffusion parameters
"""

from .config import (  # noqa: F401
    DINO_INPUT_SIZE, DINO_MEAN, DINO_STD, DINO_EMBED_DIM,
    DINO_NUM_TOKENS, DINO_PATCH_SIZE, DINO_NUM_REGISTERS,
    POINTPATCH_INPUT_SIZE, POINTPATCH_PATCH_SIZE, POINTPATCH_EMBED_DIM, POINTPATCH_NUM_TOKENS,
    COND_EMBED_DIM,
    SS_COND_NUM_TOKENS, SLAT_COND_NUM_TOKENS,
    SS_NUM_TOKENS, SS_LATENT_CHANNELS, SS_SPATIAL_RES,
    SS_MODEL_CHANNELS, SS_NUM_BLOCKS, SS_NUM_HEADS, SS_PATCH_SIZE,
    SS_IS_SHORTCUT, SS_INFERENCE_STEPS, SS_CFG_STRENGTH, SS_CFG_INTERVAL,
    SS_RESCALE_T, SS_TIME_SCALE,
    SS_SHAPE_TOKENS, SS_POSE_TOKENS_MERGED,
    SS_SHAPE_CHANNELS, SS_ROTATION_CHANNELS, SS_TRANSLATION_CHANNELS,
    SS_SCALE_CHANNELS, SS_TRANSLATION_SCALE_CHANNELS,
    SS_DECODER_LATENT_CH, SS_DECODER_CHANNELS, SS_DECODER_OUT_CH,
    SLAT_LATENT_CHANNELS, SLAT_SPATIAL_RES, MAX_VOXELS,
    SLAT_MODEL_CHANNELS, SLAT_NUM_BLOCKS, SLAT_NUM_HEADS, SLAT_PATCH_SIZE,
    SLAT_IO_BLOCK_CHANNELS, SLAT_NUM_IO_RES_BLOCKS,
    SLAT_INFERENCE_STEPS, SLAT_CFG_STRENGTH, SLAT_RESCALE_T, SLAT_TIME_SCALE,
    SLAT_MEAN, SLAT_STD,
    SPARSE_CONV_KERNEL_SIZE, SPARSE_CONV_NUM_KERNEL_ELEM,
    SPARSE_CONV_HASH_SIZE, SPARSE_CONV_MAX_NEIGHBORS,
    TIMESTEP_DIM, TIME_SCALE,
    prepare_timestep_schedule, shortcut_step_sizes,
)
