trigger:
  branches:
    include:
    - master
    - releases/*
  paths:
    exclude:
    - modules/nvidia_plugin

pr:
  branches:
    include:
    - master
    - releases/*
  paths:
    exclude:
    - modules/nvidia_plugin

resources:
  repositories:
  - repository: openvino
    type: github
    endpoint: ilya-lavrenov
    name: openvinotoolkit/openvino
    ref: setupvars

  - repository: testdata
    type: github
    endpoint: openvinotoolkit
    name: openvinotoolkit/testdata

jobs:
- job: Mac
  strategy:
    matrix:
      x86_64:
        CMAKE_OSX_ARCHITECTURES: x86_64
      # arm64:
      #   CMAKE_OSX_ARCHITECTURES: arm64
  # About 200% of total time (perfomace of Mac hosts is unstable)
  timeoutInMinutes: 180

  pool:
    vmImage: 'macOS-11'

  variables:
    system.debug: true
    VSTS_HTTP_RETRY: 5
    VSTS_HTTP_TIMEOUT: 200
    BUILD_TYPE: Release
    REPO_DIR: $(Build.Repository.LocalPath)
    OPENVINO_REPO_DIR: $(REPO_DIR)/../openvino
    MODELS_PATH: $(REPO_DIR)/../testdata
    WORK_DIR: $(Pipeline.Workspace)/_w
    BUILD_DIR: $(WORK_DIR)/build
    BIN_DIR: $(OPENVINO_REPO_DIR)/bin/intel64/$(BUILD_TYPE)
    INSTALL_DIR: $(WORK_DIR)/install_pkg
    SETUPVARS: $(INSTALL_DIR)/setupvars.sh

  steps:
  - script: |
      whoami
      uname -a
      which python3
      python3 --version
      which java
      java -version
      gcc --version
      xcrun --sdk macosx --show-sdk-version
      env
      sysctl -a
    displayName: 'System info'

  - script: |
      rm -rf $(WORK_DIR) ; mkdir $(WORK_DIR)
      rm -rf $(BUILD_DIR) ; mkdir $(BUILD_DIR)
    displayName: 'Make dir'

  - checkout: self
    clean: true
    lfs: false
    submodules: recursive
    path: openvino_contrib

  - checkout: openvino
    clean: true
    lfs: false
    submodules: recursive
    path: openvino

  - checkout: testdata
    clean: true
    lfs: true
    path: testdata

  - script: |
      brew install cython
      brew install automake
      # for ARM compute
      brew install scons
      # Speed up build
      brew install ninja

    workingDirectory: $(WORK_DIR)
    displayName: 'Install dependencies'

  - script: |
      export PATH="/usr/local/opt/cython/bin:$PATH"
      cmake -GNinja \
        -DVERBOSE_BUILD=ON \
        -DCMAKE_BUILD_TYPE=$(BUILD_TYPE) \
        -DBUILD_nvidia_plugin=OFF \
        -DOPENVINO_EXTRA_MODULES=$(REPO_DIR)/modules \
        -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 \
        -DCMAKE_OSX_ARCHITECTURES=$(CMAKE_OSX_ARCHITECTURES) \
        -DENABLE_OV_PADDLE_FRONTEND=OFF \
        -DENABLE_OV_ONNX_FRONTEND=OFF \
        -DENABLE_OV_TF_FRONTEND=OFF \
        -DENABLE_OV_TF_LITE_FRONTEND=OFF \
        -DENABLE_OV_PYTORCH_FRONTEND=OFF \
        -DENABLE_CPPLINT=OFF \
        -S $(OPENVINO_REPO_DIR) \
        -B $(BUILD_DIR)
    displayName: 'CMake'

  - script: ninja
    workingDirectory: $(BUILD_DIR)
    displayName: 'Build Mac'

  - script: ls -alR $(OPENVINO_REPO_DIR)/bin/
    displayName: 'List bin files'

  - script: cmake -DCMAKE_INSTALL_PREFIX=$(INSTALL_DIR) -P cmake_install.cmake
    workingDirectory: $(BUILD_DIR)
    displayName: 'Install'

  - script: ls -alR $(INSTALL_DIR)
    displayName: 'List install files'
  
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(INSTALL_DIR)
      artifactName: 'openvino_aarch64_mac'
    displayName: 'Publish OpenVINO AArch64 Mac package'

  - script: |
      . $(SETUPVARS) gradle clean build --info
      for d in CPU HETERO:CPU; do
        gradle test -Prun_tests -DMODELS_PATH=$(MODELS_PATH) -Ddevice=$d --info;
      done
    workingDirectory: $(REPO_DIR)/modules/java_api
    displayName: 'Java tests'
    condition: eq(variables['CMAKE_OSX_ARCHITECTURES'], 'x86_64')
