trigger:
  branches:
    include:
    - master
    - releases/*
  paths:
    exclude:
    - modules/nvidia_plugin

pr:
  branches:
    include:
    - master
    - releases/*
  paths:
    exclude:
    - modules/nvidia_plugin

resources:
  repositories:
  - repository: openvino
    type: github
    endpoint: openvinotoolkit
    name: openvinotoolkit/openvino

  - repository: testdata
    type: github
    endpoint: openvinotoolkit
    name: openvinotoolkit/testdata

jobs:
- job: Win
  timeoutInMinutes: 90

  pool:
    name: WIN_VMSS_VENV_F8S_WU2

  variables:
    system.debug: true
    VSTS_HTTP_RETRY: 5
    VSTS_HTTP_TIMEOUT: 200
    BUILD_TYPE: Release
    REPO_DIR: $(Build.Repository.LocalPath)
    OPENVINO_REPO_DIR: $(REPO_DIR)\..\openvino
    MODELS_PATH: $(REPO_DIR)\..\testdata
    WORK_DIR: $(Pipeline.Workspace)\_w
    BUILD_DIR: D:\build
    BIN_DIR: $(OPENVINO_REPO_DIR)\bin\intel64\$(BUILD_TYPE)
    MSVS_VARS_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat
    MSVC_COMPILER_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.24.28314\bin\Hostx64\x64\cl.exe
    INSTALL_DIR: $(WORK_DIR)\install_pkg
    SETUPVARS: $(INSTALL_DIR)\setupvars.bat
    CUSTOM_OP_LIB: $(BIN_DIR)\user_ov_extensions.dll
    GRADLE_VER: 7.1.1

  steps:
  - script: |
      powershell -command "Invoke-RestMethod -Headers @{\"Metadata\"=\"true\"} -Method GET -Uri http://169.254.169.254/metadata/instance/compute?api-version=2019-06-01 | format-custom"
      where python3
      python3 --version
      where python
      python --version
      where java
      java -version
      wmic computersystem get TotalPhysicalMemory
      wmic cpu list
      wmic logicaldisk get description,name
      wmic VOLUME list
      set
    displayName: 'System info'

  - script: |
      rd /Q /S $(WORK_DIR) & mkdir $(WORK_DIR)
      rd /Q /S $(BUILD_DIR) & mkdir $(BUILD_DIR)
    displayName: 'Make dir'

  - checkout: self
    clean: true
    lfs: false
    submodules: recursive
    path: openvino_contrib

  - checkout: openvino
    clean: true
    lfs: false
    submodules: recursive
    path: openvino

  - checkout: testdata
    clean: true
    lfs: true
    path: testdata

  - script: |
      rem Speed up build
      powershell -command "Invoke-WebRequest https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-win.zip -OutFile ninja-win.zip"
      powershell -command "Expand-Archive -Force ninja-win.zip"
      powershell -command "Invoke-WebRequest https://services.gradle.org/distributions/gradle-$(GRADLE_VER)-bin.zip -OutFile gradle-$(GRADLE_VER)-bin.zip"
      powershell -command "Expand-Archive -Force gradle-$(GRADLE_VER)-bin.zip"
      python -m pip install --upgrade pip
      python -m pip install -r $(OPENVINO_REPO_DIR)\src\bindings\python\src\compatibility\openvino\requirements-dev.txt
      python -m pip install -r $(OPENVINO_REPO_DIR)\src\bindings\python\requirements.txt
      python -m pip install -r $(REPO_DIR)\modules\custom_operations\tests\requirements.txt
      python -m pip install $(OPENVINO_REPO_DIR)\tools\mo
      powershell -command "Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
      choco install opencv -y
    workingDirectory: $(WORK_DIR)
    displayName: 'Install dependencies'

  - script: |
      set PATH=$(WORK_DIR)\ninja-win;%PATH%
      set OpenCV_DIR=C:\tools\opencv\build
      call "$(MSVS_VARS_PATH)" && cmake -GNinja ^
        -DCMAKE_BUILD_TYPE=$(BUILD_TYPE) ^
        -DBUILD_nvidia_plugin=OFF ^
        -DENABLE_OV_TF_FRONTEND=OFF ^
        -DENABLE_OV_ONNX_FRONTEND=OFF ^
        -DENABLE_OV_PADDLE_FRONTEND=OFF ^
        -DENABLE_OV_TF_LITE_FRONTEND=OFF ^
        -DENABLE_OV_PYTORCH_FRONTEND=OFF ^
        -DENABLE_INTEL_GPU=OFF ^
        -DENABLE_INTEL_GNA=OFF ^
        -DENABLE_CPPLINT=OFF ^
        -DENABLE_OV_ONNX_FRONTEND=ON ^
        -DOPENVINO_EXTRA_MODULES=$(REPO_DIR)/modules ^
        -DENABLE_PYTHON=ON ^
        -DCMAKE_C_COMPILER:PATH="$(MSVC_COMPILER_PATH)" ^
        -DCMAKE_CXX_COMPILER:PATH="$(MSVC_COMPILER_PATH)" ^
        $(OPENVINO_REPO_DIR)
    workingDirectory: $(BUILD_DIR)
    displayName: 'CMake OpenVINO Contrib'

  - script: dir $(OPENVINO_REPO_DIR)\temp\ /s
    displayName: 'List temp SDKs'

  - script: call "$(MSVS_VARS_PATH)" && $(WORK_DIR)\ninja-win\ninja
    workingDirectory: $(BUILD_DIR)
    displayName: 'Build OpenVINO Contrib'

  - script: dir $(OPENVINO_REPO_DIR)\bin\ /s
    displayName: 'List bin files'

  - script: cmake -DCMAKE_INSTALL_PREFIX=$(INSTALL_DIR) -P cmake_install.cmake
    workingDirectory: $(BUILD_DIR)
    displayName: 'Install OpenVINO Contrib'

  - script: dir $(INSTALL_DIR) /s
    displayName: 'List install files'

  - script: |
      call $(SETUPVARS)
      set PATH=$(WORK_DIR)\gradle-$(GRADLE_VER)-bin\gradle-$(GRADLE_VER)\bin;%PATH%
      gradle clean build --info
      gradle test -Prun_tests -DMODELS_PATH=$(MODELS_PATH) -Ddevice=CPU --info
    workingDirectory: $(REPO_DIR)\modules\java_api
    displayName: 'Java tests'

  - script: |
      call C:\tools\opencv\build\setup_vars_opencv4.cmd
      call $(SETUPVARS)
      python -m pytest -k "not sparse_conv" tests\run_tests.py
    workingDirectory: $(REPO_DIR)\modules\custom_operations
    displayName: 'Custom user operation tests'
