#!/bin/bash

GET_ROOT_DIR="git rev-parse --show-toplevel"
ROOT_DIR=$(eval $GET_ROOT_DIR)
if [ -z "$ROOT_DIR" ]; then
    cd ../..
    ROOT_DIR=$(eval $GET_ROOT_DIR)
fi
PRE_PUSH_IMPL_DIR=$ROOT_DIR/modules/cuda_plugin/utils
cd $PRE_PUSH_IMPL_DIR
./pre-push-impl.sh
exit $?
