name: Code Style
on:
  push:
    paths:
      - 'modules/java_api/**'
  pull_request:
    paths:
      - '.github/workflows/code_style.yml'
      - 'modules/java_api/**'

permissions: read-all

jobs:
  Java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Fix code java style
        uses: axel-op/googlejavaformat-action@v4
        with:
          args: "--set-exit-if-changed -a -i"
          skip-commit: true
      - name: Print diffs
        run: git --no-pager diff --exit-code
