# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Copyright

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/**'
  workflow_dispatch:

permissions: read-all

jobs:
  license-header:
    name: License header check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check license headers
        uses: apache/skywalking-eyes/header@61275cc80d0798a405cb070f7d3a8aaf7cf2c2c1 # v0.8.0
        with:
          config: .licenserc.yaml
          mode: check
          token: ${{ secrets.GITHUB_TOKEN }}
