# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Copyright

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/**'
  workflow_dispatch:

permissions: read-all

jobs:
  license-header:
    name: License header check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: '1.23.6'
          cache: false

      - name: Install License Eye
        run: go install github.com/apache/skywalking-eyes/cmd/license-eye@v0.8.0

      - name: Check license headers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: license-eye -v info -c .licenserc.yaml header check
