# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Token Merging - Test

on:
  push:
    branches:
      - master
    paths:
      - 'modules/token_merging/**'
  pull_request:
    branches: 
      - master
    paths:
      - 'modules/token_merging/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  Precommit:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create and start a virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    - name: Install dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install modules/token_merging/[tests]
    - name: Run test
      run: |
        source venv/bin/activate
        python -m pytest modules/token_merging/tests/
